---
abstract: 'An interactive shell to run Dist::Zilla commands'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Shell
recommends:
  Term::ReadLine::Gnu: 0
requires:
  Dist::Zilla: 4.300002
  Term::ReadLine: 0
  Text::ParseWords: 0
resources:
  homepage: https://github.com/dolmen/p5-Dist-Zilla-Shell
  repository: https://github.com/dolmen/p5-Dist-Zilla-Shell.git
version: 0.005
